### ISSUE TITLE
Configuration lost after container-restart

### ISSUE THREAD

**Issue by Cumulus7** [ioBroker/ioBroker.lovelace#105] opened 2020-09-10 13:03 UTC
Hi,

sorry for opening an issue - i don't know if this is not simply a user-error.

Situation: after a restart of my NAS, on which IOBroker runs inside a container, lovelace has lost its whole configuration. It is just empty :-(.

What could be the reason?

The folders  /shared and /opt/iobroker are mapped to the local file-system of my NAS:
/share/Container/shared:/shared:rw -v /share/Container/iobroker-data:/opt/iobroker

I am pretty clueless as to why the config is empty now and would like to avoid this in the future.

THX for any tips!

versions:

Lovelace 1.0.16.
Node.js 12.18.1
js-controller 3.1.5

THX and Greetings,
Markus

**Comment by Garfonso** [comment] 2020-09-10 15:09
Don't be sorry to open an issue. 

I don't think this is connected to NAS / container, though (but am not sure). The configuration is stored in the **object** database in the object `lovelace.*.configuration`. There seem to be situations where the configuration can get lost for some reason. 
Till now I was unable to reproduce it... :-( But usually you can use this information to recreate the configuration from a backup (if the object really is broken, sometimes it seems to be a browser issue, too, where a full refresh & restart of the browser help, too).

Did your NAS / Container crash? Is the object database fine otherwise? Did you edit the configuration just before it happened?

**Comment by Cumulus7** [comment] 2020-09-10 21:08
THX for the quick reply.

The NAS did not crash. It was a normal reboot during a firmware update. The Container-Station was shut down normally.
All other object-states seem normal. For example SQL-history of my weather-station data from the same day is still there.

The Lovelace configuration seems just reset.
![image](https://user-images.githubusercontent.com/45620107/92805940-d538f300-f3b9-11ea-964a-1c3daa9fd22c.png)

I did not edit the config for several days.

Ah well... time to get the backup-adapter to work again :-(
Last backup is from june [_shame on me :-)_] - i will just redo my layout.

Greetings,
Markus

**Comment by Garfonso** [comment] 2020-09-11 08:02
Can you have a look at the log file from the reboot (or the days before) if there is anything related to lovelace in it? (Or all stored logs like this: zgrep lovelace /opt/iobroker/log/*.gz )

Also there is `objects.json.bak` in `/opt/iobroker/iobroker-data` which has the object-database from the previous run, maybe you can find something in there.

**Comment by Cumulus7** [comment] 2020-09-11 08:53
Log-File: no entries concerning lovelace.
Backup: files are too new. Nothing left inside concerning the old lovelace config.

I will just redo my config.
THX everybody...

Should i close the issue?

**Comment by Garfonso** [comment] 2020-09-11 09:06
I think we can close the issue, since I do not think the loss of configuration is connected with your setup (container / NAS) and it seems we do not get more information from this particular case...

**Closed by Garfonso** 2020-09-11 09:06 UTC
