### ISSUE TITLE
Light Card ohne Dimmfunktion

### ISSUE THREAD

**Issue by nelzon101** [ioBroker/ioBroker.lovelace#49] opened 2019-11-04 22:06 UTC
Hallo
Mein Adapter hab ich sowohl via Iobroker-Adapter, als auch via Github (Expertenmodus) installiert. Beim hinzufügen mit der Karte "Light" erscheint **kein Einstellbogen über der Lampe**. Im Datenpunkt number und light pobiert. Dimmen mithilfe eines normalen sliders funktioniert.

Alles mit Chrome (PC&Tablet) ausprobiert. 

Noch jemand mit dem Problem oder gar einer Lösung hier?

Gruß Nelzon

**Comment by algar42** [comment] 2019-11-11 19:31
please try current version from git.

**Comment by dasFelix** [comment] 2019-11-14 12:39
Same here (also with current version from git). Tried 0.24 and 0.23

**Comment by dasFelix** [comment] 2019-11-14 14:01
I've tried some rollbacks.
v0.1.5 => * WORKS *
v0.2.0 => (could not install) 
--- No matching version found for iobroker.lovelace@0.2.0.npm ERR! notarget In most cases you or one of your dependencies are requestingnpm ERR! notarget a package version that doesn't exist.
v.0.2.1 => does NOT work
v0.2.3 => does NOT work

**Comment by algar42** [comment] 2019-11-14 14:14
could you please give some more details in English with maybe some pictures of what is expected and what is not working? 
and Please also try version from my repo - https://github.com/algar42/ioBroker.lovelace.git

**Comment by dasFelix** [comment] 2019-11-14 14:36
Thx. I tried also your version from your repo. Did not work as well for me :(

The enitity I've made in advance of hue.0.lightxyz.level then I add a light card but I don't get the "dim ring" above.

I would expect something like that:
![lovelace5](https://user-images.githubusercontent.com/4163534/68866122-3d646d00-06f4-11ea-8890-1c77ac750364.png)

But it looks like this:  
![lovelace4](https://user-images.githubusercontent.com/4163534/68866108-33426e80-06f4-11ea-9c76-82fb221bf5c0.png)

The generated html looks like this:
![lovelace3](https://user-images.githubusercontent.com/4163534/68866217-5c62ff00-06f4-11ea-90c4-7da51d0a4aaa.png)

And as I mentioned above with v0.1.5 it works. So I guess my other steps are correct.

**Comment by algar42** [comment] 2019-11-14 14:44
hmmm... really strange. 
here are my light object:
![image](https://user-images.githubusercontent.com/40002726/68866817-08f9ac80-0706-11ea-9552-fa893675abc4.png)
and object description for brightness:
![image](https://user-images.githubusercontent.com/40002726/68866900-23338a80-0706-11ea-94e9-c97dfd136fd9.png)

Please check how roles and object properties are assigned, e.g. units etc. 
it works for me with the code from my repo:
![image](https://user-images.githubusercontent.com/40002726/68867170-70aff780-0706-11ea-9054-79f886ad4b4a.png)

**Comment by dasFelix** [comment] 2019-11-14 15:15
I use directly the state of the child object of the hue adapter. As I see you generated some aliases and your object is manually generated. 
My object/role looks like this: (role = level.dimmer) 
![lovelace6](https://user-images.githubusercontent.com/4163534/68869677-dcd82e80-06f9-11ea-8098-740a785cc9c4.png)
I never tried this with "manual created" objects.

**Comment by algar42** [comment] 2019-11-14 15:24
Can you try the following:
1. assign some room and function at channel level
2. change role to level.brightness for bri state
3. restart lovelace
it then should detect your device automatically... probably. 

with regards to only one dimmer state - I'll take a look into code later. I did not try that.

**Comment by dasFelix** [comment] 2019-11-14 16:13
Thank you. There is some progress:
I tried what you said... I deleted the manual entity first. After I assigned some rooms and functions.
Nothing changed with hue-adapter. No light shown up. Manual entity showed the same issue (non dimmable).

I tried the same with my deCONZ adapter and the light showed up automatically. 
Also I have the "dim-ring"-thing :)
But the light is not switchable (no reaction). Also changing the dim-wheel has no function.

Then I added a manual entity again on the "level.dimmer" state. Then the light is switchable by clicking the bulb. But no dim-wheel is showing up. The same as before with the hue adapter. When I rename the role of it's default "level.dimmer" to "level.brightness" does not change anything.

I always restarted the lovelace instance when I changed something...

Lights with hue-adapter has ".bri" which has values from 0-255 and ".level" has values from 0-100(%). 

Lights with deCONZ-adapter has only one state (.bri) which has values from 0-255.

Screens:
![lovelace8](https://user-images.githubusercontent.com/4163534/68874713-f54c4700-0701-11ea-99f5-6af1798cb31b.png)

and
![lovelace7](https://user-images.githubusercontent.com/4163534/68874734-fb422800-0701-11ea-9490-f59edf291552.png)

**Comment by dasFelix** [comment] 2019-11-14 16:20
BTW: 
the manual entity light card. I can switch "OFF" the light by clicking the bulb. But it does not switch on again by another click on that bulb. But bulb-icons changes correctly if I switch the bulb manually (not with lovelance). Strange thing.

**Comment by algar42** [comment] 2019-11-14 16:34
Please try to re-install from my repo. I did some changes to manually added dimmer states..

**Comment by dasFelix** [comment] 2019-11-14 17:24
Wow a huge step forward now 👍  ;) Thank you a lot!

I tested it with all adapers I have:

Manual added dimmer states work with lights on my HUE adapter and deCONZ adapter. For the hue-lights I have to choose the [hue-lightXY].level state (bri shows correct dimmer state but I cannot change it - not an issue I guess).

I have another light connected to a shelly1 switch (relay). This has _no_ dimmer feature and it shows no dim-wheel, which is correct for a light like this. But the issue is: I can switch that light but not _on_ again. Manually switched on the bulb shows correct state. 

This are some screen shots of the "shelly light" and object
![lovelace9](https://user-images.githubusercontent.com/4163534/68880528-b622f380-070b-11ea-9adf-b5a94cd4affa.png)

Object - I have to use "[shelly-XYZ].Relay0.switch" state which has a "switch" role:
![lovelace10](https://user-images.githubusercontent.com/4163534/68880559-c33fe280-070b-11ea-8697-2af217203d8c.png)

**Comment by algar42** [comment] 2019-11-14 18:35
Cool. thank you for testing. I'll look at remaining issues when I have some time..

**Comment by algar42** [comment] 2019-11-14 18:43
for shelly, if its state is just true/false you you could try to use entity button card and assign icon manually, e.g. 'mdi:lamp'. It should work I think

**Comment by dasFelix** [comment] 2019-11-14 18:58
Thank you for your work and solution with those dimmer switches. The Shelly Thing is nice-to-have but as you recommended there is another solution/work-around for it. 
This is exactly what I tried :)
![lovelace11](https://user-images.githubusercontent.com/4163534/68887313-12404480-0719-11ea-9ddd-8e6c80616664.png)

**Comment by dasFelix** [comment] 2019-11-14 19:24
I just discovered a small issue with the dimmer light card.
I have some warnings in the iobroker Log... (No max value defined) as follows:
![lovelace12](https://user-images.githubusercontent.com/4163534/68889115-934d0b00-071c-11ea-8e6f-d4773470fb3e.png)

But there are max values in their config:
![lovelace13](https://user-images.githubusercontent.com/4163534/68889135-a19b2700-071c-11ea-8e9d-878167766ab8.png)

With the hue adapter there are no such warnings. Only with lights connected by deCONZ.

**Comment by algar42** [comment] 2019-11-14 19:35
Yes, I know about this. Try to add min, max at channel level - it looks like a place where adapter now tries to find them :)

**Comment by dasFelix** [comment] 2019-11-14 20:32
I just  // out commented the log write function in the else functions. But now I tried your approach. This works too, indeed. 
But not on the channel level - I guess you mean "device" level... 
When I have _deconz.0.lights.5_ then _.lights_ is channel and _.5_ is device. It worked on the device level (.5).

**Comment by dasFelix** [comment] 2019-11-14 20:59
sorry I was to fast with my success above :(
When I switch off the lights external (i.e. alexa) then the   
"min": 0, "max": 255, Settings on device level are gone. Deconz Adapter seems to delete those values. 

Also when I switch on/off a deconz-light by alexa the bulb in lovelace UI does not change. When I switch off the bulb remains ON. 
But when I dim the light by alexa the dim wheel changes accordingly. 

All those problems are only with deconz, not with hue adapter.

**Comment by algar42** [comment] 2019-11-15 06:57
I do not have Deconz devices, so I can only guess.. 
Am I right that now for Deconz light you have only lovelace state assigned to .bri state (level.dimmer)? 
It seems to me that Alexa sets .on state to false to switch it off and the .bri value remains unchanged. 
if it is the case there is nothing we can do in lovelace having only one dimmer state. The solution will be to make an alias to deconz light like in my example above with two states (on and bri) which will make it possible for lovelace to detect this alias device automatically as light entity with both states included..

**Comment by algar42** [comment] 2019-11-15 09:54
@dasFelix please try yet another small updated from my repo. Switching off from lovelace is slightly corrected.

**Comment by dasFelix** [comment] 2019-11-15 10:30
Thank you... I saw your system with the aliases yesterday and I like it very much. Not only because of the lights also because of the system itself. And you can calculate values like offset of temperature and things like that. But I have not very much time today to play with all the aliases. But I will try your new updated version from your repo right now and I'll keep you updated.

**Comment by dasFelix** [comment] 2019-11-15 10:50
At first sight there seems to be an improvement again 👍 

I don't know what you where aiming at but so far as I can see:
-hue lights/groups are working correctly (dim and switch and also switch off by i.e. Alexa gets feedback)
- switching on/off a shelly plugged light works now when using Light card (improvement). It also gets feedback by switching it off by alexa.
- deCONZ did not change very much: Switching on/off works, dim works. Dim gets also feedback when dimming by Alexa. But no difference is when switching on/off by alexa. There is no feedback in the UI. But I did not try deconz lights by alias. Not automatic nor manual entity. Will test that later or tomorrow :)

**Comment by WW1983** [comment] 2019-11-21 15:42
> hmmm... really strange.
> here are my light object:
> 
> and object description for brightness:
> 
> Please check how roles and object properties are assigned, e.g. units etc.
> it works for me with the code from my repo:

@algar42 ist offtopic. but can you say wich weather-card you use. the original Card dont Show icons

**Comment by algar42** [comment] 2019-11-21 15:57
@WW1983 i currently use iobroker.accuweather adapters together with weather card i developed for it.. See in readme weather section

**Comment by WW1983** [comment] 2019-11-21 16:11
> @WW1983 i currently use iobroker.accuweather adapters together with weather card i developed for it.. See in readme weather section

Thank you. I try it

**Comment by algar42** [comment] 2019-11-21 16:42
> > @WW1983 i currently use iobroker.accuweather adapters together with weather card i developed for it.. See in readme weather section
> 
> Thank you. I try it

@WW1983 , ah... and probably, if you are going to use accuweather you will also need to update type-detector (https://github.com/algar42/ioBroker.type-detector.git).  There is a pull request for accuweather type which is not yet merged to main repo :(

**Comment by WW1983** [comment] 2019-11-22 06:04
> @WW1983 i currently use iobroker.accuweather adapters together with weather card i developed for it.. See in readme weather section
> 
> Thank you. I try it
> 
> @WW1983 , ah... and probably, if you are going to use accuweather you will also need to update type-detector (https://github.com/algar42/ioBroker.type-detector.git).  There is a pull request for accuweather type which is not yet merged to main repo :(

It works. thank you :)

**Comment by algar42** [comment] 2019-11-22 06:14
@WW1983  Works as expected? Language and units are Ok? If any findings with weather please open issue for card or accuweather adapter.

**Comment by WW1983** [comment] 2019-11-22 06:27
> Works as expected? Language and units are Ok? If any findings with weather please open issue for card or accuweather adapter.

It works fine for me. Language and units are OK! If i have a Problem with the card i would open issue. thak you! Will the "Trial API" end after limited Hours?
Great work with the Adapter and Card!

**Comment by algar42** [comment] 2019-11-22 06:37
@WW1983 Trial Accuweather API allows to make 50 requests per day. Adapter makes about 30 requests per day (see its readme), so you have about 20 if you want to get weather manually - there are buttons in adapter Object for this :)

**Comment by WW1983** [comment] 2019-11-22 06:53
> @WW1983 Trial Accuweather API allows to make 50 requests per day. Adapter makes about 30 requests per day (see its readme), so you have about 20 if you want to get weather manually - there are buttons in adapter Object for this :)

Ah cool. ist enough for me :D
thank you

@dasFelix sorry das ich dein issue hier missbraucht habe

**Comment by GermanBluefox** [comment] 2019-12-06 14:59
Can it be closed?

**Comment by algar42** [comment] 2019-12-06 15:55
yes

**Comment by WW1983** [comment] 2019-12-06 15:59
Don't work for me with Hue-Lamp
<img width="418" alt="Bildschirmfoto 2019-12-06 um 16 54 25" src="https://user-images.githubusercontent.com/56581564/70336581-a9e11080-1849-11ea-8bd1-7a052beba289.png">

**Comment by WW1983** [comment] 2020-01-22 12:06
Can be closed

**Closed** 2020-01-22 12:23 UTC
